api first pass for powervs
openshift-powervs/api pull request #1
Opened 2021-06-18 19:36 UTC by clnperez

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

2021-06-18 19:37 UTC, clnperez commented
@mkumatag @Karthik-K-N PTAL

2021-06-23 07:00 UTC, mkumatag requested changes

2021-06-23 07:00 UTC, mkumatag commented on config/v1/types_infrastructure.go
> +	Region string `json:"region"`
This may not be that straightforward, but time being I'm okay with this value. Will change it if required.

2021-06-23 07:00 UTC, mkumatag commented on config/v1/types_infrastructure.go
> +	// There must be only one ServiceEndpoint for a service.
this includes even the ibm cloud service endpoints as well, like your iam etc.. here are the few endpoints we use for the pvsadm: https://github.com/ppc64le-cloud/pvsadm/blob/master/pkg/client/environments.go#L14:L16

2021-06-23 21:00 UTC, clnperez commented
@mkumatag thanks for the review. I'm not clear though on what changes I need to make.

2021-06-24 04:42 UTC, mkumatag commented
> @mkumatag thanks for the review. I'm not clear though on what changes I need to make.

Let's merge as is, will change it later if anything required.

2021-06-24 16:07 UTC, clnperez commented on config/v1/types_infrastructure.go
> +	Region string `json:"region"`
i think i should at least add a zone. for some regions it looks like this is mandatory. ok if i add that, and then merge?

2021-06-25 05:07 UTC, mkumatag commented on config/v1/types_infrastructure.go
> +	Region string `json:"region"`
yes, you can.

2021-06-25 22:50 UTC, clnperez commented
Merging. Added a Zone field.

2021-06-25 22:50 UTC, merged

2021-07-29 13:43 UTC, Prashanth684 commented on config/v1/types_infrastructure.go
> +	Region string `json:"region"`
i think like other platforms you need apiserverinternalip, ingressip and possibly nodednsip if it is using it's own DNS server

2021-07-29 13:50 UTC, Prashanth684 commented
config/v1/0000_10_config-operator_01_infrastructure.crd.yaml  needs to be modified as well for the platform to be recognized

2021-07-29 18:04 UTC, Prashanth684 commented on config/v1/types_infrastructure.go
> +	Region string `json:"region"`
on second thought -no, these are only for on-prem